JC19-354-Init-anime-app-table-view
saritasa-nest/camp-js-2022-dao-duong pull request #1
Opened 2022-07-07 06:45 UTC by daoduong-saritasa

Initialize anime app with table view

2022-07-07 08:24 UTC, artem-sotnichenko-saritasa requested changes

2022-07-07 08:24 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +export const paginateButton = (pages: number): void => {
You come up with a better name, like `renderPaginateButton`. Read wiki https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#naming-functions

2022-07-07 08:50 UTC, TienLuu-Saritasa requested changes

2022-07-07 08:50 UTC, TienLuu-Saritasa commented on apps/vanilla/src/pages/index.css
> +} */
Please remove your comment

2022-07-07 08:50 UTC, TienLuu-Saritasa commented on apps/vanilla/src/scripts/anime.ts
> +export const getAnime = async(limit: number, page: number, sortSetting: SortSetting): Promise<Pagination<Anime>> => {
> To increase the cohesion of these pagination-related properties, it would be reasonable to unify them into a single entity. Also, [we prefer avoiding ordered params](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#how-to-pass-arguments-to-functionsmethods).

2022-07-07 08:50 UTC, TienLuu-Saritasa commented on libs/core/models/aired.ts
> +type InitArgsAired = OmitImmerable<Aired>;
You could create DateRange and type with it everything related to start and end dates
```
/** Period of time. */
export interface DateRange {

  /** Start of the period. */
  readonly start: Date;

  /** End of the period. */
  readonly end: Date;
}
```

2022-07-07 09:04 UTC, daoduong-saritasa commented on apps/vanilla/src/scripts/interfaces.ts
> +}
I only need to add readonly for SortOption right? Cause SortSetting property will be changed when choosing sort options

2022-07-07 09:46 UTC, TienLuu-Saritasa commented on apps/vanilla/src/scripts/interfaces.ts
> +}
If you need to update your sort options, you can use destructuring, f.e:
```
{
  ...options,
  text: "your text"
}
```

2022-07-07 09:52 UTC, daoduong-saritasa commented on libs/core/models/aired.ts
> +type InitArgsAired = OmitImmerable<Aired>;
I think it's just naming confusion, will it acceptable if I change Aired class to DateRange, or I have to create new DateRange interface

2022-07-07 10:27 UTC, TienLuu-Saritasa commented on libs/core/models/aired.ts
> +type InitArgsAired = OmitImmerable<Aired>;
Yeah, sorry for wrong example, you could change Aired class to DateRange

2022-07-07 13:02 UTC, TienLuu-Saritasa commented on apps/vanilla/src/scripts/anime.ts
> +    `anime/anime/?limit=${limit}&offset=${offset}&ordering=${sortSettings.direction}${sortSettings.option}`,
Please check [this](https://masteringjs.io/tutorials/axios/get-query-params). The 2nd parameter to axios.get() is the [Axios options](https://github.com/axios/axios#request-config): Axios will serialize options.params and add it to the query string

2022-07-07 13:07 UTC, TienLuu-Saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  const pageBtn = document.querySelectorAll('.page');
Please [avoid contractions](https://wiki.saritasa.rocks/frontend/languages/ts-js/naming#avoid-contractions)

2022-07-07 13:10 UTC, TienLuu-Saritasa commented on libs/core/dtos/anime.dto.ts
> +  readonly type: 'GENRES';
Please create `enum` or `union`for this `type`

2022-07-07 13:15 UTC, TienLuu-Saritasa commented on libs/core/dtos/aired.dto.ts
> +  readonly start: Date;
> Are you sure the BE sends you `Date` object? I believe it's a `string`

2022-07-07 13:56 UTC, timofei-maximov-saritasa requested changes

2022-07-08 02:46 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/pages/index.css
> +  height: 150px;
It can make the picture display scaling, pls check it

2022-07-08 02:59 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/global/components.css
> +  --default-layout-width: 90%;
It look unusual, could you move it into variables.css

2022-07-08 04:07 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/scripts/API.ts
> +  headers: { 'Api-Key': `${import.meta.env.VITE_API_KEY}`, 'Accept': 'application/json' },
I see we have eslint warning.
We could use disable eslint
// eslint-disable-next-line @typescript-eslint/naming-convention

2022-07-08 04:16 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/scripts/functions.ts
> + * Change state of the order direction.
I think we do not need to have Annotations on this variables, IDE is warning "it can be Null"
we can check:
 if (sortDirection === null) {
  throw new Error .... 
 }

2022-07-08 04:21 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +export const renderPaginateButton = (pages: number): void => {
Please check 'wrapper' value can be "null"

2022-07-08 04:22 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  paginateButton.forEach(element => {
please check
element.getAttribute('index') can be "null" value

2022-07-08 04:24 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/scripts/sort.ts
> +  const sortOption = document.querySelector<HTMLSelectElement>('#sort-option');
Its value could be 'null', so we could not use Annotations here

2022-07-08 04:26 UTC, thanhnguyen-saritasa commented on apps/vanilla/src/scripts/sort.ts
> +        PAGINATION_STATE.active = FIRST_PAGE;
Seen SORT_SETTINGS has read-only property. so can not assign value here

2022-07-08 05:06 UTC, daoduong-saritasa commented on apps/vanilla/src/scripts/functions.ts
> + * Change state of the order direction.
I have created a new utility function assert for null. Please check commit [6612870]

2022-07-08 06:46 UTC, golovachev-yaroslav requested changes

2022-07-08 06:46 UTC, golovachev-yaroslav commented on apps/vanilla/src/global/components.css
>  .links {
Is it class for many links or for singular element?

2022-07-08 06:46 UTC, golovachev-yaroslav commented on apps/vanilla/src/global/index.css
> +@import url("../../../.././node_modules/materialize-css/dist/css/materialize.min.css");
Firstable, need to import external libs, otherwise it will override developer's style.

2022-07-08 06:46 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/index.css
> +#pagination-wrapper {
Do not use id for styling. Id good for JS.
Also, id could not repeat on a page many times.

2022-07-08 06:46 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/pagination.ts
> +    <li index=${FIRST_PAGE} class="waves-effect pagination__item"><a>First</a></li>
Tag `a` requires `href` attribute, maybe replace it with another tag?

2022-07-10 12:33 UTC, daoduong-saritasa commented on apps/vanilla/src/global/components.css
>  .links {
It's the default css in the boilerplate. I don't use it but I forgot to delete

2022-07-11 05:11 UTC, golovachev-yaroslav requested changes

2022-07-11 05:11 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/anime.ts
> +  const params = new URLSearchParams({ limit: limit.toString(), offset: (limit * (page - 1)).toString(), ordering });
I think it would be better `(limit * (page - 1)).toString()` make as const.

2022-07-11 06:12 UTC, panov-aleksey-saritasa requested changes

2022-07-11 06:12 UTC, panov-aleksey-saritasa commented on libs/core/interfaces/pagination.ts
> +  readonly ordering: string;
It's not clear from the docs what the `ordering` property is.

2022-07-11 06:12 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/sort.ts
> +      const data: Pagination<Anime> = await getAnime(paginationConfig);
Same about type annotations.

2022-07-11 06:12 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +export const renderPaginateButton = (pages: number): void => {
Prefer using [function declaration](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#use-function-declaration) instead

2022-07-11 06:12 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/pages/index.css
> +}
If you are using [BEM](https://en.bem.info/), consider making use of [modifiers](https://en.bem.info/methodology/quick-start/#modifier). Right now it's quite implicit what this class is about, where it's going to be used

2022-07-11 06:12 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/anime.ts
> +  const params = new URLSearchParams({ limit: limit.toString(), offset: (limit * (page - 1)).toString(), ordering });
Consider making a mapper function that would convert `PaginationConfig` to the object with `limit` and `offset` properties

2022-07-11 06:12 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/anime.ts
> +  return PaginationMapper.fromDto<AnimeDto, Anime>(data, animeDto => AnimeMapper.fromDto(animeDto));
```suggestion
  return PaginationMapper.fromDto(data, animeDto => AnimeMapper.fromDto(animeDto));
```

2022-07-11 06:30 UTC, elena-dragunova approved these changes

2022-07-11 09:28 UTC, TienLuu-Saritasa requested changes

2022-07-11 09:28 UTC, TienLuu-Saritasa commented on apps/vanilla/src/global/variables.css
> +  --white-color: #fff;
Please rename your variable
https://wiki.saritasa.rocks/frontend/languages/css/#naming

2022-07-15 04:25 UTC, TienLuu-Saritasa approved these changes

2022-07-15 04:27 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/global/variables.css
> +  --active-text-color: #fff;
Please group your variables

2022-07-15 04:27 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/pages/index.html
> +      <div class="sort__select-element">
You should use label instead of just div(class="sort__select-element"). That way "Sort by" would be associated with select, that improves accessibility.

2022-07-15 04:27 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/animeTable.ts
> +       </tr>
Please fix indentation

2022-07-15 04:27 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +    });
Please group you code lines, it is hard to read.

2022-07-15 04:27 UTC, artem-sotnichenko-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  const paginateButton = document.querySelectorAll('.pagination__item');
You should use button for interactivity, `li` is not designed for this purpose. You could just put `button` inside `li`, or don't use `ul` here, because pagination is not a list.

2022-07-15 05:16 UTC, daoduong-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  const paginateButton = document.querySelectorAll('.pagination__item');
It's materialize pagination. Should I rewrite it?

2022-07-15 15:18 UTC, chernodub commented on apps/vanilla/src/scripts/pagination.ts
> + * */
Pls make sure your code is formatted properly

2022-07-15 15:23 UTC, chernodub commented on apps/vanilla/src/scripts/API.ts
> +import axios from 'axios';
Usually we prefer not to uppercase names of the files, even if abbreviations are used, please stick to that

2022-07-15 15:24 UTC, chernodub commented on apps/vanilla/src/scripts/pagination.ts
> +export function renderPaginateButton(pages: number): void {
As far as I understand, this function not only renders the whole pagination controller, instead of a single button. Please keep your naming and implementation consistent

2022-07-15 15:30 UTC, chernodub commented on apps/vanilla/src/scripts/pagination.ts
> +  let maxRight = (currentPage + HALF_NUMBER_OF_PAGES);
Please revise the naming of these variables. Think from a perspective of a code reader, I see the function `renderPaginationButton`, then I see `maxRight` and `maxLeft` inside. This logic is very hard to follow. 

After you wrote a function, consider re-reading it like a small narrative, try to keep your plot consecutive. You are a narrator in a way :)

2022-07-15 15:34 UTC, chernodub commented on apps/vanilla/src/scripts/pagination.ts
> +  const paginateButton = document.querySelectorAll('.pagination__item');
[@daoduong-saritasa you should always use interactive elements for handling user events](https://wiki.saritasa.rocks/frontend/languages/html#use-button-for-handling-user-clicks). It is not clear what do you mean by `materialize pagination`? You apply an event listener to a `li` element, this is the problem

2022-07-15 15:36 UTC, chernodub commented on apps/vanilla/src/scripts/search.ts
> +  assertNonNullish(searchButtonElement);
The properties above are not nullable, right? If so, you don't need these assertions

2022-07-15 15:37 UTC, chernodub commented on apps/vanilla/src/scripts/search.ts
> +export function performSearching(): void {
As far as I see, this function initializes search elements with event listeners. Consider revising the name, please.

2022-07-15 15:38 UTC, chernodub commented on apps/vanilla/src/scripts/sort.ts
> +/**  Render sort options.*/
Please keep your formatting consistent for every JSDoc
```
/** Render sort options. */
```

2022-07-15 15:41 UTC, chernodub commented on libs/core/dtos/anime.dto.ts
> +/** Aired DTO. */
Why is this comment needed?

2022-07-15 15:46 UTC, chernodub commented on libs/core/dtos/anime.dto.ts
> +}
Seems that you've used `enum` wrong. Checkout [this demo](https://www.typescriptlang.org/play?#code/KYOwrgtgBAKgngB2FA3gKClA5DAalgGg2wHlcBBQ4rAWTIEkBRKzLAZQAVGBhe8gGRakAcpSKsaAVTb1uVAL5o0AYwD2IAM6qANsAB021QHMAFPCR68ASiA), click `run` and see the log. The real values for these properties are numbers. But BE sends you strings. So, for your case you could use a [string union alias](https://www.typescriptlang.org/docs/handbook/2/template-literal-types.html). 

Please revise [enums article](https://www.typescriptlang.org/docs/handbook/enums.html#handbook-content)

2022-07-16 05:31 UTC, daoduong-saritasa commented on apps/vanilla/src/scripts/search.ts
> +  assertNonNullish(searchButtonElement);
The querySelector always return the element or null so it's nullable

2022-07-16 06:27 UTC, daoduong-saritasa commented on apps/vanilla/src/scripts/pagination.ts
> +  let maxLeft = (currentPage - HALF_NUMBER_OF_PAGES);
I don't understand about "make it global" part. Here I use const and let for declaration, I thought it declare a block-scoped variable and I declare it in a function.

2022-07-16 07:34 UTC, daoduong-saritasa commented on apps/vanilla/src/global/index.css
> +@import url("../../../.././node_modules/materialize-css/dist/css/materialize.min.css");
When I remove the dots I get this error. I search and saw a PR that fix this error but I still get this
![image](https://user-images.githubusercontent.com/108647643/179345133-263914a5-6eb5-4fa6-81cd-bf7031c165b2.png)

2022-07-18 14:46 UTC, chernodub commented on apps/vanilla/src/scripts/pagination.ts
> +  let maxLeft = (currentPage - HALF_NUMBER_OF_PAGES);
@daoduong-saritasa I'm talking about `HALF_NUMBER_OF_PAGES` constant. It is only used in this file, so there is not point making it globally available for the whole application

2022-07-19 17:10 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/animeTable.ts
> +  const tableBody = dataset.results.reduce((previousValue: string, currentValue: Anime): string => `${previousValue}
and again about the names, compare, let's say somewhere in another function you see the same line, but we don't use Typescript:
```const tableBody = dataset.results.reduce((previousValue, currentValue)=> `${previousValue}<tr><td>${currentValue.name}</td></tr>```
Will it be easy clear from your code what it's doing? 
or you see this:
```const tableBody = studioList.results.reduce((previousBody, studio) => `${previousBody}<tr><td>${studio.name}</td></tr>```
It seems to me that the second one is obvious, even without Typescript, but it is impossible to understand the first one without analyzing where our function is called and what will be passed to it in the parameter `dataset`.

2022-07-19 17:11 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/animeTable.ts
> +  const tableBody = dataset.results.reduce((previousValue: string, currentValue: Anime): string => `${previousValue}
and second thing, since the parameters `previousValue` and `currentValue` use the same term `Value`, then it is logical to expect that this is the previous and current values of the same thing, right? well, i.e. for example the previous Anime and the current Anime. But you have completely different entities, the first is the accum of the table body, and the second is Anime, which means it is desirable to reflect this in the variable names so as not to confuse other developers.

2022-07-19 17:28 UTC, pavelzadorin-saritasa commented on libs/core/models/dateRange.ts
> +  public readonly start: string;
If this is a date, then it is logical to store it in the Date type, because it is much more convenient to work with it in the future. For example, you don’t have to pass a string to the convertDate function and convert it to a date there in order to get the string again, but in a different format ...
This is one of the reasons why we separate the model layer from the repository layer. A model is a data structure that is convenient for us, for our application, for working in JS. And it doesn’t matter that the data comes from the API in a different format (after all, only simple data structures are allowed in JSON), for this there are Mappers that convert raw / inconvenient data into a format convenient for us.

2022-07-19 17:39 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/sort.ts
> +        page: FIRST_PAGE,
it turns out when you sort your page is reset to the first? I do not think that this is justified, the number of pages will not change from using sorting and we may well leave the user on the current open page, this will be a good UX.
resetting pagination is justified for filtering and searching, because the number of pages changes, but not for sorting.
for example: https://mui.com/material-ui/react-table/#data-table

2022-07-20 12:16 UTC, pavelzadorin-saritasa approved these changes

2022-07-20 12:16 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/pages/index.ts
> +  const anime = await getAnime(paginationConfig);
`anime` is a singular noun (1 film), but you get a list of anime, so you have to use plurar here, better naming would be `animes` or `animeList`

2022-07-20 12:16 UTC, pavelzadorin-saritasa commented on apps/vanilla/src/scripts/animeTable.ts
> +  const tableBody = dataset.results.reduce((previousBody: string, currentData: Anime): string => `${previousBody}
`dataset` and `currentData` are not semantic names, please take a closer look at my previous [comment](https://github.com/saritasa-nest/camp-js-2022-dao-duong/pull/1#discussion_r924766602), I'm sure the option I proposed will improve the readability of the code.

2022-07-20 18:34 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-05 05:46 UTC, chernodub approved these changes

2022-08-05 06:25 UTC, merged