JC19-462 - Init app and authorization - [React]
saritasa-nest/camp-js-2022-dao-duong pull request #10
Opened 2022-08-26 06:18 UTC by daoduong-saritasa

2022-08-26 08:45 UTC, timofei-maximov-saritasa requested changes

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/api/services/animeService.ts
> +  }: AnimeListQueryParams): Promise<Pagination<Anime>> {
Do you really need destructuring here? Can't you just use an object?

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.module.css
> +  margin-bottom: 15px !important;
Can you explain why do you need `important` here?

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +            onClick={formik.submitForm}
There is no need to add this handler, since your button has `submit` type.

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/pages/Login/Login.tsx
> +  const httpError = useAppSelector(selectAuthError);
Let's use it inside our form compopent. You coupled implicitly coupled components. It is not clear how does this error appears in state.

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/pages/Login/Login.tsx
> +    event?: React.SyntheticEvent | Event,
```suggestion
    event?: SyntheticEvent | Event,
```

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/features/auth/routes.tsx
> +export const authRoutes: RouteObject[] = [
```suggestion
  })));
  
export const authRoutes: RouteObject[] = [
```

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/features/user/pages/Profile/Profile.tsx
> +  if (isLoading || !user) {
Please, avoid implicit type casting for `user`

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/features/user/pages/Profile/Profile.tsx
> +  if (isLoading || !user) {
```suggestion
  }, [dispatch]);
  
  if (isLoading || !user) {
```

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/routes/guards/AuthGuard.tsx
> +  if (user || token) {
Same about type-casting

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/routes/guards/NoAuthGuard.tsx
> +    return <Navigate to={redirect} replace/>;
```suggestion
    };
    
    return <Navigate to={redirect} replace/>;
```

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/shared/components/MyNavbar/MyNavbar.tsx
> +    useState<null | HTMLElement>(null);
Something weird with formatting.
```suggestion
  const [anchorElementUser, setAnchorElementUser] = useState<null | HTMLElement>(null);
```

2022-08-26 08:45 UTC, timofei-maximov-saritasa commented on apps/react/src/store/auth/slice.ts
> +          state.error = HttpErrorMapper.fromDto(error.response?.data);
Let's map it service. Redux contains your business logic. By mapping error here you are violating abstraction

2022-08-26 08:51 UTC, golovachev-yaroslav approved these changes

2022-08-26 08:51 UTC, golovachev-yaroslav commented on apps/react/src/shared/components/MyNavbar/MyNavbar.module.css
> +  color: #fff;
Please use css var.

2022-08-26 09:36 UTC, daoduong-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.module.css
> +  margin-bottom: 15px !important;
I use it to override Mui styles. But I've figured out other way

2022-08-26 09:45 UTC, daoduong-saritasa commented on apps/react/src/shared/components/MyNavbar/MyNavbar.tsx
> +    useState<null | HTMLElement>(null);
It's prettier formatting. I just auto format and it turn out like this.

2022-08-26 10:29 UTC, golovachev-yaroslav approved these changes

2022-08-26 10:29 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +    <>
Looks like unnecessary `<></> ` They good for multiple child components
 
```
return (
  <>
    <Avatar />
    <Dropdown />
  </>
)
```

2022-08-26 13:31 UTC, golovachev-yaroslav requested changes

2022-08-26 13:31 UTC, golovachev-yaroslav commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +        <br />
Br good for new line for content formatting, much better to add padding/margin.

2022-08-29 02:11 UTC, timofei-maximov-saritasa approved these changes

2022-08-29 02:11 UTC, timofei-maximov-saritasa commented on apps/react/src/routes/guards/NoAuthGuard.tsx
> +  const hasTokenFromLocalStorage = TokenService.hasToken();
Let's avoid `LocalStorage` in variable name here. `TokenService` can use any storage internally. You don't what is going on inside `TokenSevice`, since implementation is encapsulated.

2022-08-29 02:11 UTC, timofei-maximov-saritasa commented on apps/react/src/shared/components/MySnackbar/MySnackbar.tsx
> +    event?: React.SyntheticEvent | Event,
```suggestion
    event?: SyntheticEvent | Event,
```

2022-08-29 02:11 UTC, timofei-maximov-saritasa commented on apps/react/src/store/auth/slice.ts
> +      .addCase(login.rejected, (state, action) => {
You can specify action type to avoid type casting. `action: PayloadAction<HttpError>`

2022-08-30 03:50 UTC, golovachev-yaroslav approved these changes

2022-08-30 03:59 UTC, pavelzadorin-saritasa requested changes

2022-08-30 03:59 UTC, pavelzadorin-saritasa commented on apps/react/src/shared/components/MySnackbar/MySnackbar.tsx
> +export const MySnackbar = memo(MySnackbarComponent);
`my snackbar` is a semantically weak name, how exactly does that reflect the meaning of this component?

2022-08-30 03:59 UTC, pavelzadorin-saritasa commented on apps/react/src/shared/components/MyNavbar/MyNavbar.tsx
> +export const MyNavbar = memo(MyNavbarComponent);
`my navbar` is a semantically weak name, how exactly does that reflect the meaning of this component?

2022-08-30 03:59 UTC, pavelzadorin-saritasa commented on apps/react/src/features/genres/pages/GenresPage/GenresPage.tsx
> +      <MyNavbar />
It seems to me that this component would be necessary for all pages of the site (excepts auth) if there were a lot of them (and genres, and anime, etc.) and in order not to describe it in each individual page, it makes sense to transfer `Navbar` to the root layout or root router.

2022-08-30 03:59 UTC, pavelzadorin-saritasa commented on apps/react/src/features/auth/utils/error.ts
> +  if (error.data) {
`error.data` this is actually DTO object: http://jing.saritasa.com/PavelZadorin/screen_2022-08-30_10-22-47_tPjz.png
therefore, this processing is in fact a mapping that you call from the UI layer, this is a violation of the abstraction of application layers.
Errors are not fundamentally different from other application entities and should be converted into convenient models in the same place where the response from the API is processed.

2022-08-30 03:59 UTC, pavelzadorin-saritasa commented on apps/react/src/features/auth/components/LoginForm/LoginForm.tsx
> +    if (httpError instanceof HttpError) {
I don't see an error message when I enter invalid credentials, please check your API error handling

2022-08-30 03:59 UTC, pavelzadorin-saritasa commented on apps/react/src/features/auth/components/RegisterForm/RegisterForm.tsx
> +      <MySnackbar
This method will be repeated in each form, I would like to avoid code repetition.
So encapsulation of the Snackbar display logic inside the Snackbar looks reasonable, at the moment the parent component (e.g. RegisterForm) define the Open status and CloseHandler and passes them to the Snackbar, but really does the parent need to operate with these entities at all? why can't the Snackbar manage the opening status itself internally and handle the closing? From the parent, then only the message and type of error will be needed, well, maybe HideDuration yet and the forms will become much simpler.
May be conditional rendering will be enough for opening Snackbar:
```
{error &&
  <MySnackbar
        message={error}
        severity='error'
    />
}
```

2022-08-30 05:40 UTC, golovachev-yaroslav requested changes

2022-08-30 05:40 UTC, golovachev-yaroslav commented on apps/react/src/App.tsx
> +import { MyNavbar } from './shared/components';
Bad mame of the component. Please avoid my, our, etc. Much better to call it AppNavbar.

2022-08-30 07:29 UTC, golovachev-yaroslav approved these changes

2022-09-05 07:04 UTC, pavelzadorin-saritasa approved these changes

2022-09-26 08:06 UTC, closed without merging