JC19-482 - Anime list management - [React]
saritasa-nest/camp-js-2022-dao-duong pull request #12
Opened 2022-09-05 04:21 UTC by daoduong-saritasa

2022-09-05 11:10 UTC, artem-sotnichenko-saritasa approved these changes

2022-09-05 11:46 UTC, golovachev-yaroslav requested changes

2022-09-05 11:46 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeList/AnimeList.module.css
> +{
Please format styles:
`.anime-list::-webkit-scrollbar-track {`

2022-09-05 11:46 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeListControls/AnimeListControl.tsx
> +      {...other}
If you use rest operator please add it as the first.
`<div {...other} role="tabpanel" hidden...`
Otherwise rest props override props which appears before.

2022-09-05 11:46 UTC, golovachev-yaroslav commented on apps/react/src/features/anime/components/AnimeListControls/components/Type/Type.tsx
> +import { AnimeType } from '@js-camp/core/models/anime/anime';
`anime/anime'` - need to improve, it lokks strange.
You can add it into index.ts.

2022-09-05 11:46 UTC, golovachev-yaroslav commented on apps/react/src/store/anime/dispatchers.ts
> +  'anime_page/fetch',
camelCase will looks better.

2022-09-06 04:42 UTC, golovachev-yaroslav approved these changes

2022-09-12 12:46 UTC, pavelzadorin-saritasa approved these changes

2022-09-12 12:46 UTC, pavelzadorin-saritasa commented on apps/react/src/features/anime/components/AnimeListControls/components/Sort/Sort.tsx
> +  /** Title in english. */
incorrect jsdoc

2022-09-12 12:46 UTC, pavelzadorin-saritasa commented on apps/react/src/features/anime/components/AnimeListControls/components/Sort/Sort.tsx
> +  /** Title in japanese. */
incorrect jsdoc

2022-09-12 12:46 UTC, pavelzadorin-saritasa commented on apps/react/src/shared/hooks/useLastItemOnScreen.ts
> +const useLastItemOnScreen = (options: Object) => {
jsdoc please

2022-09-26 08:06 UTC, closed without merging