JC19-357-authorization
saritasa-nest/camp-js-2022-dao-duong pull request #2
Opened 2022-07-13 04:57 UTC by daoduong-saritasa

Authorization feature

2022-07-13 05:34 UTC, golovachev-yaroslav requested changes

2022-07-13 05:34 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/register/index.html
> +    <title>Vite App</title>
I think there should be title related to register.

2022-07-13 05:34 UTC, golovachev-yaroslav commented on apps/vanilla/src/pages/profile/profile.ts
> +      <img class="user-avatar" src="${user.avatar}" alt="User Avatar" />
`alt` could be a user full name.

2022-07-13 05:34 UTC, golovachev-yaroslav commented on apps/vanilla/src/scripts/functions.ts
> +      <button class="logout-btn btn-right">Logout</button>
missed button type

2022-07-13 05:34 UTC, golovachev-yaroslav commented on apps/vanilla/src/services/authService.ts
> +      navigate(Url.Login);
Login shouldn't know about navigation or other actions.

2022-07-13 05:34 UTC, golovachev-yaroslav commented on apps/vanilla/src/services/authService.ts
> +      navigate(Url.Login);
The same with navigation.

2022-07-14 05:38 UTC, elena-dragunova approved these changes

2022-07-15 02:46 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-16 22:24 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/constants.ts
> +}
```suggestion
/** Type of token. */
export enum Token {
  Refresh = 'REFRESH_TOKEN',
  Access = 'ACCESS_TOKEN',
}

/** Available url. */
export enum Url {
  Base = '/',
  Login = '/login/',
  Register = '/register/',
}
```

2022-07-16 22:24 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/functions.ts
> +  return false;
Let's use early return pattern.
```suggestion
 if (token === null) {
   return false;
 }
 const isValid = await AuthService.verifyToken(token);
 return isValid;
```

2022-07-16 22:24 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/scripts/functions.ts
> + */
Please, format your docs

2022-07-16 22:24 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/authService.ts
> +    const { data } = await api.get('/users/profile/', { headers: { Authorization: `Bearer ${StorageService.get(Token.Access)}` } });
You can use [axios interceptors](https://axios-http.com/docs/interceptors) to improve authorization flow

2022-07-16 22:24 UTC, timofei-maximov-saritasa commented on libs/core/dtos/httpError.dto.ts
> +}
Please, add docs

2022-07-18 15:13 UTC, chernodub requested changes

2022-07-18 15:13 UTC, chernodub commented on apps/vanilla/src/services/errorService.ts
> +  export function createErrorElement(errorElement: HTMLInputElement | HTMLFormElement, err: string): void {
The function name tells us that the function is going to `create` something, so me, as a code reader, would assume it's going to return the created element. But the signature tells the opposite, it has `void` as a return type. Consider adjusting the name, keep it consistent with the type signature at all times

2022-07-19 06:44 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/login/login.ts
> +assertNonNull(loginForm);
When I remove the function, loginForm will have an error "Object possibly null". I think it because the querySelector always return Element or null. So maybe I just keep it this way.

2022-07-28 08:08 UTC, chernodub commented on apps/vanilla/src/pages/register/index.html
> +          <input type="text" name="first_name" placeholder="First name" autocomplete="on">
For better consistency, we usually prefer `kebab-case` for naming inputs. I see that in your case you're relying on the backend provided validation info, which is not bad. But, for future, I recommend not to rely on BE provided property keys on your template. Instead, you should create some kind of key mapping. Otherwise, if BE team decides that they need to change something, you would have to refactor several files in your application.

2022-07-28 08:08 UTC, chernodub commented on apps/vanilla/src/services/storageService.ts
> +    return await JSON.parse(value) as T;
`JSON.parse` is sync, so you can omit `await`

2022-07-28 08:08 UTC, chernodub commented on libs/core/dtos/httpError.dto.ts
> +  readonly code?: string;
@daoduong-saritasa I see that you "resolved" the comment. But is it really fixed? I believe no. In this case you simply duplicated comments with your property names, this is not very useful. Please always try to give some semantic meaning via documentation. `detail`  is a _human-readable representation of error_, `data` is _object containing messages related to incorrect fields_ and etc.

2022-07-28 08:21 UTC, daoduong-saritasa commented on apps/vanilla/src/pages/profile/profile.ts
> +    </li>
@chernodub My bad, I fixed it on another branch but I thought I was fixed on this branch. I'll updated it right away

2022-08-05 05:55 UTC, chernodub approved these changes

2022-08-05 05:55 UTC, chernodub commented on apps/vanilla/src/namespaces/navbar.ts
> +  }
As far as I understand, this function can only be called one time after `renderNavbar` is called (otherwise, several buttons would be added). And, it is already called in `renderNavbar`, therefore there is no point making it exportable, right?

2022-08-05 09:13 UTC, merged