Feature/jc19 380 add searching
saritasa-nest/camp-js-2022-dao-duong pull request #4
Opened 2022-07-18 03:26 UTC by khoanguyen-saritasa

2022-07-18 07:13 UTC, artem-sotnichenko-saritasa approved these changes

2022-07-18 07:13 UTC, artem-sotnichenko-saritasa commented on libs/core/interfaces/pagination.ts
> +  /** Query string. */
Please be consistent. I don't see why description for dto and model should differ.

2022-07-19 07:56 UTC, panov-aleksey-saritasa approved these changes

2022-07-19 07:56 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/anime.ts
> +  const params = PaginationMapper.toDto({ limit, page, ordering, search });
Consider not making ordering and search part of pagination config, since they are unrelated things

2022-07-19 07:56 UTC, panov-aleksey-saritasa commented on apps/vanilla/src/scripts/anime.ts
> +  const params = PaginationMapper.toDto({ limit, page, ordering, search });
You can make a auxiliary interface for anime searching, something like `AnimeSearchParams` or `AnimeSearchConfig` and include there search, sorting and pagination properties

2022-07-23 00:57 UTC, dbitkovski requested changes
I haven't seen all your PR's so you probably answered this question before. What does `scripts` folder stand for? I can understand `pages`, `models`, `dto`, etc but not that one. As far as we make programs using javascript / typescript all our files are scripts :cat: It seems like you can put any file in this folder and it will work
Let's improve this and come up with a better name. Probably, you'll need to create several folders and move each file in an appropriate one

2022-07-23 00:57 UTC, dbitkovski commented on apps/vanilla/src/global/index.css
> +@import url("../../../.././node_modules/materialize-css/dist/css/materialize.min.css");
Is there a way to add alias for the project root folder to avoid such paths?
If we can't add alias format the path though, you have redundant `./` before `node_modules`

2022-07-23 00:57 UTC, dbitkovski commented on apps/vanilla/src/pages/index.html
> +      <!-- Select section -->
This comment does not provide any useful information, consider removing it

2022-07-23 00:57 UTC, dbitkovski commented on apps/vanilla/src/pages/index.ts
> +  localStorage.setItem('sort', '');
I don't think it's a good idea to store this information in `localStorage`. If you need to keep state it's better to do that right in component and pass data from parent element to pagination / search components.

2022-07-23 00:57 UTC, dbitkovski commented on apps/vanilla/src/scripts/pagination.ts
> +      renderAnimeTable(data);
You did a great job but we can make you pagination component much better.
You see, technically your pagination component does not care about entities it works with. `Anime`, `Animals`, `Users` it's all the same for pagination since the only responsibility of this component is to change page of the data a user sees.
As you might understand I want you to move the logic of getting new anime list outside of this. It should be something like this:
```
element.addEventListener('click', () => {
  ...
  // handle new pagination state
  const paginationConfig = { ... };
  paginationChange(paginationConfig); // This is a callback that should be passed by the component that uses `renderPaginationButton`
});
```

2022-07-25 00:15 UTC, pavel-romanov8 requested changes

2022-07-25 00:15 UTC, pavel-romanov8 commented on apps/vanilla/src/pages/index.html
> +      <input type="search" class="search_input"/>
`_input` is not a modifier. It doesn't describe any behaviour or state. Let's make it an element instead

2022-07-25 00:15 UTC, pavel-romanov8 commented on apps/vanilla/src/scripts/API.ts
> +  // eslint-disable-next-line @typescript-eslint/naming-convention
Not sure why do we need to disable the rule, just follow it

2022-07-25 00:15 UTC, pavel-romanov8 commented on libs/core/models/pagination.ts
> +  public readonly previous: string | null;
As far as I know, you are not using `next` and `previous` in any way. Consider removing it

2022-07-25 00:15 UTC, pavel-romanov8 commented on libs/core/models/dateRange.ts
> +  /** Anime end date. */
As I understand, the `DateRange` model stand for simple period of time and shouldn't be tight to any other entity. If that is the case, let's remove mentions of `anime` from the doc strings

2022-07-25 00:15 UTC, pavel-romanov8 commented on libs/core/mappers/pagination.mapper.ts
> +    } as PaginationOptionsDto;
Not sure why do we need such casting here

2022-07-25 00:15 UTC, pavel-romanov8 commented on libs/core/models/dateRange.ts
> +  public readonly start: string;
It is better to store date in our models as `Date` object instead of plain strings. That way we can easily manipulate them

2022-07-25 00:15 UTC, pavel-romanov8 commented on libs/core/dtos/anime.dto.ts
> +  'NOT_YET_AIRED',
It looks kinda strange. Usually we are using enums like a key-value pair. Here it could be:
```ts
Status {
  Airing = 'AIRING'
 ....
}
```
That way, we are not forced to use values directly in our code base, which brings naming consistency. If you want to use just strings, I suggest you creating union type instead. Also, consider naming it like `AnimeStatusDto`, because it is not clear what just `Status` stands for if you are facing it in a different file + we are explicitly saying that this status only used within repository layer and shouldn't leak to other parts of the app

2022-07-25 00:15 UTC, pavel-romanov8 commented on apps/vanilla/src/scripts/variables.ts
> +  AiredStart = 'aired__startswith',
Not sure why we are using BE specific names here

2022-08-05 06:25 UTC, merged