feature/JC19-359-display-detail
saritasa-nest/camp-js-2022-dao-duong pull request #5
Opened 2022-07-20 07:57 UTC by daoduong-saritasa

Display anime detail

2022-07-21 03:56 UTC, gevorg-gevorgyan-saritasa requested changes

2022-07-21 03:56 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/detail/detail.ts
> +  renderTitle(animeDetail.englishTitle ? animeDetail.englishTitle : animeDetail.japaneseTitle);
```suggestion
  renderTitle(animeDetail.englishTitle || animeDetail.japaneseTitle);
```

2022-07-21 03:56 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/login/index.html
> +          </label>
```suggestion
          <label> 
            Email
            <input type="email" name="email" placeholder="Email" required autocomplete="on">
          </label>
```

2022-07-21 03:56 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/scripts/animeTable.ts
> +      localStorage.setItem(CLICKED_ANIME, animeId);
Consider using your `StorageService` to work with `localStorage`

2022-07-21 03:56 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/services/animeService.ts
> +   * @param imageURL Youtube trailer Id.
Update docs please

2022-07-21 03:56 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/pages/index.ts
> +  localStorage.setItem(PaginationLocalStorage.active, FIRST_PAGE.toString());
Use `StorageService` here

2022-07-21 03:56 UTC, gevorg-gevorgyan-saritasa commented on apps/vanilla/src/services/storageService.ts
> +  export async function setToken(token: TokenDto): Promise<void> {
Why you need to make all this functions `async`?

2022-07-24 10:54 UTC, timofei-maximov-saritasa commented on libs/core/models/anime/animeDetail.ts
> +export class AnimeDetail extends Immerable {
This is extended `anime` type, let's extend it from `anime` to reduce code duplication

2022-07-24 10:54 UTC, timofei-maximov-saritasa commented on libs/core/models/auth/register.ts
> +export interface Register{
```suggestion
export interface Register {
```

2022-07-24 10:54 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/services/animeService.ts
> +    const animeDetailResponse = await api.get(`anime/anime/${id}/`);
`get` method accepts generic

2022-07-24 10:54 UTC, timofei-maximov-saritasa commented on apps/vanilla/src/pages/detail/detail.ts
> +  assertNonNull(animeId);
What if user will use direct link to alime details? You can use query params to retrieve anime id

2022-10-01 02:04 UTC, merged