JC19-414 - Anime List Management - Angular
saritasa-nest/camp-js-2022-dao-duong pull request #7
Opened 2022-08-03 07:48 UTC by daoduong-saritasa

2022-08-04 08:40 UTC, timofei-maximov-saritasa commented on apps/angular/src/core/services/anime.service.ts
>    }
I think that it should be located in your anime component, since router is ui related thing. Also you already have method which is the opposite of this.

2022-08-05 07:38 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +  public readonly subscriptionDestroy$: Subject<boolean> = new Subject();
It should be private, because it's should be used only within component

2022-08-11 11:26 UTC, artem-sotnichenko-saritasa approved these changes

2022-08-11 11:26 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +  public readonly sortObservers$ = new BehaviorSubject<Sort>(INITIAL_SORT);
You shouldn't expose subjects because it's unsafe. Make them private and if you use them in a template, create observables from subject with `.asObservable()`.

2022-08-11 11:26 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +  /** Destroy subscriptions. */
Prefer using `/** @inheritdoc */` for angular lifecycle hooks.

2022-08-15 05:37 UTC, panov-aleksey-saritasa approved these changes

2022-08-15 05:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +        this.length = animeResponse.count;
Please, try to avoid side effects whenever it's possible. Actually, in this case you could revise your approach a bit:
```ts
const animePage$ = this.params$.pipe(
  switchMap(params => this.animeService.fetchAnime(params)),
  // shareReplay is needed here so that animePage$ stream would be executed only once
  // between multiple subscribers (animeList$ and length$ in this case)
  // https://www.learnrxjs.io/learn-rxjs/operators/multicasting/sharereplay
  shareReplay({ refCount: true, bufferSize: 1 }),
)

this.animeList$ = animePage$.pipe(map(({ results }) => results));
this.length$ = animePage$.pipe(map(({ count }) => count));    
```

2022-08-15 05:37 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/anime.service.ts
> +    );
Do you need `animeResponse$` variable? Maybe return stream right away?
```suggestion
    return this.apiService.get<PaginationDto<AnimeDto>>(path, params).pipe(
      map(animes =>
        PaginationMapper.fromDto(animes, animeDto =>
          AnimeMapper.fromDto(animeDto))),
    );
```

2022-08-15 10:54 UTC, chernodub requested changes
Good job!

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.html
> +<mat-form-field appearance="outline" class="search__form-field" color="accent">
Seems that you're using BEM elements but don't have the blocks. Elements can not exist without their blocks

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.html
> +<ng-template #Loading>
Please prefer pascal case for template names

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.html
> +    [matSortDirection]="(sort$ | async)!.direction"
[Please avoid non-null assertions](https://wiki.saritasa.rocks/frontend/languages/ts-js/best-practices#avoid-non-null-and-type-assertions)

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +const DEBOUNCE_TIME = 700;
Since these properties always come in a group, maybe it would be a good idea unifying them in a single entity?

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +      ),
Please prefer creational `combineLatest` over `combineLatestWith` to explicitly show that you wait for all 4 streams to emit

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +        ),
Seems like `valueChanges` + `startWith` repeats, maybe create a util for that?

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +const DEBOUNCE_TIME = 700;
Too generic name for `DEBOUNCE_TIME`, you have a lot of streams in the component, I believe you should specify what are you debouncing?

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +      map(([currentPage, _search, _filter, sort]) => {
Seems quite implicit that you're waiting for all 4, but, actually, need only 1 stream. Try to somehow represent that in your code, either by better naming, or docs

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +          ordering: (sort.direction === 'desc' ? '-' : '') + sort.active,
Seems like this is a knowledge about the BE implementation. It should not leak into your component (UI layer) https://wiki.saritasa.rocks/frontend/frameworks/architecture/. Maintaining such stuff is hard. In case BE team decides to change the symbol, your UI layer would have to be refactored, weird, right?

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +  public readonly length$ = this._length$.asObservable();
Prefer `protected` properties if they are used only on template

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +  private readonly _length$ = new BehaviorSubject(INITIAL_LENGTH);
Seems like it's never actually used. You reassign the `length$` in your `constructor`

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +    // Declare side effects
Pls avoid obvious comments, otherwise you'll have to maintain both comments and code. This multiplies the amount of work to 2

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +      }),
We prefer `tap` for side effects, since it does not transform the value

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +  public readonly currentPage$ = this._currentPage$.asObservable();
I believe it won't be a problem if you just use a subject, without an observable. To make sure other components/classes might not access this, you could make it `protected`

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +      .pipe(takeUntil(this.subscriptionDestroy$))
Check out this tool https://github.com/ngneat/until-destroy

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +        direction: params['ordering'].includes('-') ? 'desc' : 'asc',
You'd be able to avoid this nasty mapping after you uncouple your UI code from BE-provided syntax

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +    window.scrollTo({
Please avoid direct access to browser API. Your application may also be run in SSR context, by Node. And this code will fail since Node context does not have `window`. Consider using injection:
```ts

import { Inject } from '@angular/core';
import { DOCUMENT } from '@angular/common';

export class MyClass {

  private window: Window;

  constructor(@Inject(DOCUMENT) private document: Document) {
     this.window = this.document.defaultView;
  }

  check() {
    console.log(this.document);
    console.log(this.window);
  }

}
```

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/core/interceptors/apiKey.interceptor.ts
> +    req.headers.set('Api-Key', this.apiConfig.apiKey);
`headers.set` is an immutable operation, so it won't mutate the object, but return a new one. Therefore, your api key was not applied here

2022-08-15 10:54 UTC, chernodub commented on apps/angular/src/core/services/api.service.ts
>  }
Usually, we never replace network layer in Angular because provides a very powerful built in network system. So, please, avoid this inter-layer :) But good thinking!!

2022-08-16 03:32 UTC, daoduong-saritasa commented on apps/angular/src/app/features/anime/table/table.component.ts
> +      ),
According to rxjs docs, combineLatest will be deprecated soon. They will remove it in v8 and recommend replacing it with combineLatestWith. So is it important to change this?

2022-08-20 03:12 UTC, dbitkovski commented on apps/angular/src/core/services/navigate.service.ts
> +export class NavigateService {
What benefits the abstraction gives to you? I believe that when we create wrap-classes we try to achieve some goals. Using 3rd-party libraries we don't want our app to know what exactly we use under the hood. It also allows us to encapsulate some logic and provide only required API methods.
Angular is the main tool we use while development the app, so hiding its parts is strange. And probably we'll never change angular router to something else :cat:

2022-08-20 03:12 UTC, dbitkovski commented on libs/core/interfaces/option.ts
> +export interface Option {
If it's a sort option, it's better to name interface `SortOption`.
Your documentation should add meaning to the name of the entity it describes. In this case, the name doesn't give any information and all the work is shifted to the documentation, which is not correct.

2022-08-25 09:49 UTC, chernodub commented on apps/angular/src/app/features/anime/table/table.component.ts
> +      ),
Didn't know about that, thanks for clarification. Do it your way then :)

2022-09-13 12:15 UTC, chernodub approved these changes

2022-09-14 02:02 UTC, merged