JC19-434 - Authorization - Angular
saritasa-nest/camp-js-2022-dao-duong pull request #8
Opened 2022-08-09 09:57 UTC by daoduong-saritasa

2022-08-10 09:02 UTC, artem-sotnichenko-saritasa requested changes

2022-08-10 09:02 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/shared/components/navbar/navbar.component.html
> +        </a>
You can add `mat-raised-button` on the `<a>`. That way your link would look like a button, and behave like a link.

2022-08-10 09:02 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/shared/components/navbar/navbar.component.ts
> +      .pipe(tap(() => this.navigateService.navigateToLogin()))
I think you forgot to add `takeUntil(this.subscriptionDestroyed$)`

2022-08-11 04:32 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/anime/anime.component.html
> -<h1 class="title">Anime</h1>
FYI, if you want to be semantically correct, but at the same time don't want for an element to appear on the screen, you could add the `visually-hidden` utility css class to your app and use it. Basically it hides an element from UI, but it's still could be accessible, for example, for screen reader users
```css
.visually-hidden {
  /*
    To preserve a11y, hide radio button only visually
    https://www.sarasoueidan.com/blog/inclusively-hiding-and-styling-checkboxes-and-radio-buttons/
  */
  clip: rect(0 0 0 0);
  clip-path: inset(100%);
  height: 1px;
  overflow: hidden;
  position: absolute;
  white-space: nowrap;
  width: 1px;
  margin: 0;
}
```

2022-08-11 04:32 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/auth/login/login.component.html
> +  <mat-card>
BEM element could not be used without a block

From [the BEM docs](https://en.bem.info/methodology/quick-start/#element)
> A composite part of a block that can't be used separately from it.

2022-08-11 04:32 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/auth/login/login.component.ts
> +      password: ['', Validators.required],
If you don't use services anywhere except the constructor, you could remove `private readonly`. This way services would be treated as function arguments and won't be declared as class properties
```suggestion
  public constructor(
    private readonly authService: AuthService,
    private readonly navigateService: NavigateService,
    private readonly errorService: ErrorService,
    private readonly changeDetectorRef: ChangeDetectorRef,
    private readonly snackBar: MatSnackBar,
    formBuilder: FormBuilder,
  ) {
    this.loginForm = formBuilder.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required],
```

2022-08-11 04:32 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/auth/login/login.component.ts
> +  public submitForm(): void {
On Angular projects we usually use `on` prefix for event handlers
```suggestion
  /** Handle form submission. */
  public onFormSubmit(): void {
```

2022-08-11 04:32 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/auth/login/login.component.ts
> +      .subscribe();
Consider doing navigation on the `next` or `complete` callbacks. This way you explicitly declare what behavior you expect  when a stream emits a value or finishes completely
```suggestion
      .login(this.loginForm.value as Login)
      .pipe(
        catchError((error: unknown) => of(this.handleError(error))),
        takeUntil(this.subscriptionDestroyed$),
      )
      .subscribe({
        next: () => this.navigateService.navigateToHome(),
        // complete: () => this.navigateService.navigateToHome()
      });
```

2022-08-11 04:32 UTC, panov-aleksey-saritasa commented on apps/angular/src/app/features/auth/register/register.component.html
> +<div class="register__container">
Same thing about element without a block

2022-08-11 04:32 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/navbar/navbar.component.css
> +  z-index: 10;
https://wiki.saritasa.rocks/frontend/languages/css#explain-why-tricks-are-used-z-index-important

2022-08-11 04:32 UTC, panov-aleksey-saritasa commented on apps/angular/src/shared/components/navbar/navbar.component.ts
> +/** Login component. */
Wrong docs

2022-08-11 04:32 UTC, panov-aleksey-saritasa commented on apps/angular/src/core/services/jwt.service.ts
> +  private readonly tokenSubject$ = new ReplaySubject<Token | null>(1);
Usually we omit things such as *subject*, *stream*, *observable* and etc. for stream names, since it's already clear what it is from the type declaration. In your case I suppose you could rename it to `tokenUpdated$`

2022-08-11 06:57 UTC, daoduong-saritasa commented on apps/angular/src/app/features/anime/anime.component.html
> -<h1 class="title">Anime</h1>
I move it onto navbar so I remove it here

2022-08-11 07:01 UTC, daoduong-saritasa commented on apps/angular/src/app/features/auth/login/login.component.ts
> +        catchError((error: unknown) => of(this.handleError(error))),
It's seem like the catchError require return Observable but my handleError function return void. So I use of here to change return to observable

2022-08-15 03:28 UTC, daoduong-saritasa commented on apps/angular/src/app/features/auth/login/login.component.ts
> +      .subscribe();
I tried your way but it will always redirect even login fail.

2022-08-17 03:53 UTC, artem-sotnichenko-saritasa approved these changes
Nice 404 page 🤯

2022-08-17 03:53 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/app/features/auth/login/login.component.html
> +            placeholder="Email"
Placeholder shouldn't just repeat label, better to place example of email here.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#placeholder

2022-08-17 03:53 UTC, artem-sotnichenko-saritasa commented on apps/angular/src/core/services/error.service.ts
> +    }
```suggestion
    if (error instanceof HttpErrorResponse && error.error !== undefined) {
      return HttpErrorMapper.fromDto(error.error);
    }
```

2022-09-26 08:06 UTC, closed without merging